### ISSUE TITLE
NetBSD Live/install image with Mate Desktop

### ISSUE THREAD

**Issue by jaypatelani** [tsutsui/netbsd-teokureliveimage#1]
Hello,
Thanks for creating Live image scripts. Are you interested in creating live/install image with Mate desktop? also in English version of your current work?

Regards,
Jay

**Comment by tsutsui** [comment]
The necessary work to prepare other environments is:
1) to make sure what binary packages should be installed
2) to prepare necessary configuration files (dot files in the skel dir used by useadd(8) command, or system-wide config in /etc or /usr/pkg/etc etc.)

Language settings are LANG environment and fonts settings, so it should be trivial.

These work will be done by demand and they will appear in forks or branches as independent projects, as you have already done.
Thanks,
