### ISSUE TITLE
mkliveimage.sh Tooldir changed

### ISSUE THREAD

**Issue by jaypatelani** [tsutsui/netbsd-teokureliveimage#2]
Hi,

On NetBSD 8.0 amd64 TOOLDIR is:

TOOLDIR=/usr/src/obj/tooldir.NetBSD-8.0-amd64

**Comment by tsutsui** [comment]
To build multiple archtecture targets (i386 and x86_64 for example) from single source tree, it is recommended to set "OBJMACHINE=yes" and "USR_OBJMACHINE=yes" in /etc/mk.conf.
(see also liveimagefiles/etc/mk.conf in the code tree)

In that case the default TOOLDIR is /usr/src/obj.${MACHINE}/tooldir.[HOST-OS].${MACHINE}.
Ideally we should pull TOOLDIR definitions from src/share/mk/bsd.own.mk, but for now manual editing is simple solution..
